// <auto-generated />
using System;
using Forms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forms.Data.Migrations
{
    [DbContext(typeof(CoursesDbContext))]
    [Migration("20231211043658_ManyToManyChangeOnDeletes")]
    partial class ManyToManyChangeOnDeletes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forms.Models.CourseSchedules", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("scheduleId")
                        .HasColumnType("int");

                    b.HasKey("code", "scheduleId");

                    b.HasIndex("scheduleId");

                    b.ToTable("CourseSchedules");
                });

            modelBuilder.Entity("Forms.Models.Courses", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("preRequirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Forms.Models.Schedules", b =>
                {
                    b.Property<int>("scheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("scheduleId"));

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("currentEnrollment")
                        .HasColumnType("int");

                    b.Property<DateTime>("deadLine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endTIme")
                        .HasColumnType("datetime2");

                    b.Property<string>("instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("startTIme")
                        .HasColumnType("datetime2");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("scheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Forms.Models.CourseSchedules", b =>
                {
                    b.HasOne("Forms.Models.Courses", "Course")
                        .WithMany("CourseSchedule")
                        .HasForeignKey("code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forms.Models.Schedules", "Schedule")
                        .WithMany("CourseSchedules")
                        .HasForeignKey("scheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Forms.Models.Courses", b =>
                {
                    b.Navigation("CourseSchedule");
                });

            modelBuilder.Entity("Forms.Models.Schedules", b =>
                {
                    b.Navigation("CourseSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
